# Generated by Django 5.0.6 on 2024-06-09 16:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Aluno',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('nome', models.CharField(max_length=255)),
                ('senha', models.CharField(max_length=128)),
                ('email', models.CharField(max_length=50, unique=True)),
                ('tipoAcesso', models.CharField(default='aluno', editable=False, max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Curso',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('nome', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Indicador',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('nome', models.CharField(max_length=100)),
                ('descricao', models.CharField(max_length=1000)),
            ],
        ),
        migrations.CreateModel(
            name='Instituicao',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('nome', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Pessoa',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('nome', models.CharField(max_length=255)),
                ('email', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Script',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('nome', models.CharField(max_length=100)),
                ('descricao', models.CharField(max_length=5000)),
            ],
        ),
        migrations.CreateModel(
            name='ControleBot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bot_pode_responder', models.BooleanField(default=True)),
                ('id_aluno', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='gemini.aluno')),
            ],
        ),
        migrations.AddField(
            model_name='aluno',
            name='curso',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gemini.curso'),
        ),
        migrations.CreateModel(
            name='Coordenador',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('nome', models.CharField(max_length=255)),
                ('senha', models.CharField(max_length=128)),
                ('email', models.CharField(max_length=50, unique=True)),
                ('tipoAcesso', models.CharField(default='coordenador', editable=False, max_length=255)),
                ('curso', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gemini.curso')),
                ('instituicao', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gemini.instituicao')),
            ],
        ),
        migrations.AddField(
            model_name='aluno',
            name='instituicao',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gemini.instituicao'),
        ),
        migrations.CreateModel(
            name='Mensagem',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('texto_mensagem', models.CharField(max_length=10000)),
                ('data_hora', models.DateTimeField()),
                ('quem_enviou', models.CharField(max_length=255)),
                ('id_aluno', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='gemini.aluno')),
                ('id_coordenador', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='gemini.coordenador')),
            ],
        ),
        migrations.CreateModel(
            name='Pergunta',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('user', models.CharField(max_length=100)),
                ('pergunta', models.CharField(max_length=200)),
                ('resposta', models.TextField(blank=True, editable=False)),
                ('indicador', models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='indicador', to='gemini.indicador')),
            ],
        ),
        migrations.CreateModel(
            name='Relatorio',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('data_inicial', models.DateField()),
                ('data_final', models.DateField()),
                ('indicadores', models.ManyToManyField(to='gemini.indicador')),
            ],
        ),
        migrations.CreateModel(
            name='Setor',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('nome', models.CharField(max_length=150)),
                ('pessoas', models.ManyToManyField(related_name='pessoas', to='gemini.pessoa')),
            ],
        ),
    ]
