# Generated by Django 5.0.4 on 2024-04-08 01:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gemini', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='pergunta',
            name='resposta',
            field=models.TextField(blank=True, editable=False),
        ),
    ]
