# Generated by Django 5.0.6 on 2024-06-10 00:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gemini', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pergunta',
            name='indicador',
        ),
        migrations.CreateModel(
            name='Conversa',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('status', models.BooleanField(default=True)),
                ('id_indicador', models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='gemini.indicador')),
            ],
        ),
        migrations.AddField(
            model_name='mensagem',
            name='id_conversa',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='gemini.conversa'),
        ),
    ]
