# Generated by Django 5.0.4 on 2024-04-08 01:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gemini', '0002_pergunta_resposta'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pergunta',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
