# Generated by Django 5.0.4 on 2024-04-14 20:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gemini', '0004_indicador_pessoa_script_usuario_relatorio_setor'),
    ]

    operations = [
        migrations.AddField(
            model_name='usuario',
            name='email',
            field=models.CharField(default='email', max_length=50),
        ),
    ]
