# Generated by Django 5.0.6 on 2024-06-16 20:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('gemini', '0004_alter_conversa_data_hora'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='conversa',
            name='status',
        ),
    ]
