# Generated by Django 5.0.4 on 2024-04-14 22:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gemini', '0005_usuario_email'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='setor',
            name='pessoas',
        ),
        migrations.AddField(
            model_name='setor',
            name='pessoas',
            field=models.ManyToManyField(related_name='pessoas', to='gemini.pessoa'),
        ),
    ]
