# Generated by Django 5.0.4 on 2024-05-19 22:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gemini', '0007_pergunta_indicador'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pergunta',
            name='pergunta',
            field=models.CharField(max_length=10000),
        ),
    ]
