# Generated by Django 5.0.4 on 2024-05-19 23:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gemini', '0008_alter_pergunta_pergunta'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pergunta',
            name='resposta',
            field=models.TextField(blank=True),
        ),
    ]
