# Generated by Django 5.0.4 on 2024-05-19 23:37

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gemini', '0009_alter_pergunta_resposta'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pergunta',
            name='indicador',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='indicador', to='gemini.indicador'),
        ),
        migrations.AlterField(
            model_name='pergunta',
            name='pergunta',
            field=models.TextField(max_length=10000),
        ),
    ]
